@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">
                    <h3>Reports Dashboard</h3>
                </div>
                <div class="card-body">
                    @if(session('success'))
                        <div class="alert alert-success">
                            {{ session('success') }}
                        </div>
                    @endif

                    <!-- Report Generation Forms -->
                    <div class="row mb-4">
                        <!-- Patient Statistics -->
                        <div class="col-md-6">
                            <div class="card">
                                <div class="card-header">
                                    <h5>Patient Statistics</h5>
                                </div>
                                <div class="card-body">
                                    <form action="{{ route('reports.patients') }}" method="GET">
                                        <div class="form-group mb-3">
                                            <label for="date_range">Date Range</label>
                                            <select name="date_range" id="date_range" class="form-control">
                                                <option value="today">Today</option>
                                                <option value="week">This Week</option>
                                                <option value="month">This Month</option>
                                                <option value="year">This Year</option>
                                            </select>
                                        </div>
                                        <button type="submit" class="btn btn-primary">Generate Report</button>
                                    </form>
                                </div>
                            </div>
                        </div>

                        <!-- Inventory Report -->
                        <div class="col-md-6">
                            <div class="card">
                                <div class="card-header">
                                    <h5>Inventory Report</h5>
                                </div>
                                <div class="card-body">
                                    <form action="{{ route('reports.inventory') }}" method="GET">
                                        <div class="form-group mb-3">
                                            <label for="category">Category</label>
                                            <select name="category" id="category" class="form-control">
                                                <option value="all">All Categories</option>
                                                <option value="Medicine">Medicine</option>
                                                <option value="Equipment">Equipment</option>
                                                <option value="Supplies">Supplies</option>
                                            </select>
                                        </div>
                                        <button type="submit" class="btn btn-primary">Generate Report</button>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>

                    <!-- Recent Reports List -->
                    <div class="card mt-4">
                        <div class="card-header">
                            <h5>Recent Reports</h5>
                        </div>
                        <div class="card-body">
                            <table class="table table-bordered">
                                <thead>
                                    <tr>
                                        <th>Report ID</th>
                                        <th>Type</th>
                                        <th>Generated Date</th>
                                        <th>Generated By</th>
                                        <th>Actions</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach($reports as $report)
                                    <tr>
                                        <td>{{ $report->id }}</td>
                                        <td>{{ $report->type }}</td>
                                        <td>{{ $report->created_at->format('Y-m-d H:i:s') }}</td>
                                        <td>{{ $report->user->name }}</td>
                                        <td>
                                            <a href="{{ route('reports.show', $report->id) }}" class="btn btn-info btn-sm">View</a>
                                            <a href="{{ route('reports.download', $report->id) }}" class="btn btn-success btn-sm">Download</a>
                                            <form action="{{ route('reports.destroy', $report->id) }}" method="POST" class="d-inline">
                                                @csrf
                                                @method('DELETE')
                                                <button type="submit" class="btn btn-danger btn-sm" onclick="return confirm('Are you sure?')">Delete</button>
                                            </form>
                                        </td>
                                    </tr>
                                    @endforeach
                                </tbody>
                            </table>
                            {{ $reports->links() }}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection